### ISSUE TITLE
直接run 所有的loss都是nan

### ISSUE THREAD

**Issue by ghost** [dreamilk/ANN#3]
Welcome to mechine learning
train_image = 60000 train_lable = 60000
test_image = 10000 test_lable = 10000
Training Epoches = 10 LearningRate = 0.100000 BatchSize = 16 Shuffle = 1
TrainDataSize = 60000 TestDataSize = 10000
[1|10] TotalLoss nan Accuracy 0.098000
[2|10] TotalLoss nan Accuracy 0.098000
[3|10] TotalLoss nan Accuracy 0.098000
[4|10] TotalLoss nan Accuracy 0.098000
[5|10] TotalLoss nan Accuracy 0.098000

**Comment by dreamilk** [comment]
重新编译一下，再试试

**Comment by ghost** [comment]
嗯，重新编译之后好了。。。为啥

**Comment by dreamilk** [comment]
> 嗯，重新编译之后好了。。。为啥

当除数为0时，结果就是nan。
说明反向传播过程，有0，而每个神经元的初始值是随机的。重新随机一次，可能就不会出现这种情况了。 这种情况的概率很小

**Comment by ghost** [comment]
good
